# Use postgres/example user/password credentials
# Command for run: docker compose up -d
version: '3.1'

services:

  ba_adminer:
    container_name: ba_adminer
    image: adminer
    restart: always
    ports:
      - 1080:8080

  ba_db:
    container_name: ba_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: bapass
    ports: 
      - 1432:5432
